name: actions

on:
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: composer install
